# Generated by Django 4.2.18 on 2025-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_record_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
    ]
