# Generated by Django 4.2.18 on 2025-01-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_record_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='catagory',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Health', 'Health'), ('Education', 'Education'), ('Shopping', 'Shopping'), ('Salary', 'Salary'), ('Travel', 'Travel'), ('Utility', 'Utility'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Gifts', 'Gifts'), ('Other', 'Other')], default='', max_length=20),
        ),
    ]
