# Generated by Django 4.2.18 on 2025-01-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_record_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='income',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Income', max_length=10),
        ),
    ]
