# Generated by Django 4.2.18 on 2025-01-29 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0009_alter_record_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user_id',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
