# Generated by Django 4.2.18 on 2025-01-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_record_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user_id',
        ),
    ]
