# Generated by Django 4.2.18 on 2025-01-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_record_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='userid',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
